FROM python:3.13.5

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 8000

RUN useradd app
USER app

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]