// initialize a hash map of team names to the team logos to be able to display to our frontend
const hashMap = new Map([
  ["Hawks", "./logos/Atlanta_Hawks_logo.svg"],
  ["Celtics", "./logos/Boston_Celtics.svg"],
  ["Nets", "./logos/Brooklyn_Nets_primary_icon_logo_2024.svg"],
  ["Hornets", "./logos/Charlotte_Hornets_(2014).svg"],
  ["Bulls", "./logos/Chicago_Bulls_logo.svg"],
  ["Cavaliers", "./logos/Cleveland_Cavaliers_logo.svg"],
  ["Mavericks", "./logos/Dallas_Mavericks_logo.svg"],
  ["Nuggets", "./logos/Denver_Nuggets.svg"],
  ["Warriors", "./logos/Golden_State_Warriors_logo.svg"],
  ["Rockets", "./logos/Houston_Rockets.svg"],
  ["Pacers", "./logos/Indiana_Pacers.svg"],
  ["Pistons", "./logos/Logo_of_the_Detroit_Pistons.svg"],
  ["Clippers", "./logos/Los_Angeles_Clippers_(2024).svg"],
  ["Lakers", "./logos/Los_Angeles_Lakers_logo.svg"],
  ["Grizzlies", "./logos/Memphis_Grizzlies.svg"],
  ["Heat", "./logos/Miami_Heat_logo.svg"],
  ["Bucks", "./logos/Milwaukee_Bucks_logo.svg"],
  ["Timberwolves", "./logos/Minnesota_Timberwolves_logo.svg"],
  ["Pelicans", "./logos/New_Orleans_Pelicans_logo.svg"],
  ["Knicks", "./logos/New_York_Knicks_logo.svg"],
  ["Thunder", "./logos/Oklahoma_City_Thunder.svg"],
  ["Magic", "./logos/Orlando_Magic_logo.svg"],
  ["76ers", "./logos/Philadelphia_76ers_logo.svg"],
  ["Suns", "./logos/Phoenix_Suns_logo.svg"],
  ["Trail Blazers", "./logos/Portland_Trail_Blazers_logo.svg"],
  ["Kings", "./logos/SacramentoKings.svg"],
  ["Spurs", "./logos/San_Antonio_Spurs.svg"],
  ["Raptors", "./logos/Toronto_Raptors_logo.svg"],
  ["Jazz", "./logos/Utah_Jazz_logo_2025.svg"],
  ["Wizards", "./logos/Washington_Wizards_logo.svg"],
]);
export default hashMap;


